#!/usr/bin/env python
import os
import pwd
import sys
import traceback

import requests


def main():
    scriptname = os.path.basename(sys.argv[0])
    with os.fdopen(3) as infile:
        data = infile.read(512).split('\0')
    username, password = data[:2]
    resp = requests.get(
        'https://www.weasyl.com/api/whoami',
        headers={'X-Weasyl-API-Key': password})
    if resp.status_code != 200:
        return 1
    if resp.json()['login'] != username:
        return 1
    try:
        pwent = pwd.getpwnam(username)
    except KeyError:
        return 1
    os.environ['USER'] = pwent.pw_name
    os.environ['HOME'] = pwent.pw_dir
    os.environ['SHELL'] = pwent.pw_shell
    if scriptname == 'checkpassword-weasylapi-dovecot':
        os.environ['userdb_uid'] = str(pwent.pw_uid)
        os.environ['userdb_gid'] = str(pwent.pw_gid)
    else:
        os.initgroups(pwent.pw_name, pwent.pw_gid)
        os.setgid(pwent.pw_gid)
        os.setuid(pwent.pw_uid)
        os.chdir(pwent.pw_dir)
    os.execvp(sys.argv[1], sys.argv[1:])


try:
    sys.exit(main() or 111)
except KeyboardInterrupt:
    sys.exit(2)
except Exception:
    traceback.print_exc(file=sys.stderr)
    sys.exit(111)
